### ISSUE TITLE
Build Issue: missing include for "get_us_ticker_data"

### ISSUE THREAD

**Issue by sjauhri** [husarion/rosbot-firmware-new#1]
After completing all necessary steps mentioned in README including 'mbed update master', a compilation issue is observed when building using VSCode.

On examination the error log is:
Compile [ 81.3%]: ws2812b-effects.cpp
[Error] ws2812b-effects.cpp@67,54: 'get_us_ticker_data' was not declared in this scope

For now, adding the include "#include "us_ticker_api.h"" in the file: ws2812b-effects.cpp in the '/lib/AnimationManager/ws2812b-dma-driver' folder seems to solve this problem and I am able to build successfully.

What is the proper fix for this?

**Comment by byq77** [comment]
The `ws2812b-dma-driver` dependency was not updated.  aefc80a3489032ec66420be7f5c4f8c94c63151d fixes the issue. Thanks for the feedback.
