### ISSUE TITLE
ROS2 Roadmap

### ISSUE THREAD

**Issue by piraka9011** [husarion/rosbot-firmware-new#2]
Are there any plans to port this over to ROS2?

**Comment by byq77** [comment]
Yes, we've already experimented with ROS2 and eProsima Micro XRCE-DDS: https://micro-xrce-dds.readthedocs.io/en/latest/. However I cannot tell you exactly when we will release ros2 version of ROSbot firmware. 

A small request, please post this kind of questions/feature requests on the community forum not here. This is not a place for that.

**Comment by piraka9011** [comment]
> A small request, please post this kind of questions/feature requests on the community forum. Thanks.

Will do, thanks :)
