### ISSUE TITLE
fatal: reference is not a tree: facde70041a530749fbc59ace2700b376ceb7983

### ISSUE THREAD

**Issue by ashishk88** [husarion/rosbot-firmware-new#3]
I get this when I run the `mbed update master` command inside the `lib` folder. Any help to resolve this will be much appreciated.

**Comment by byq77** [comment]
Hi, indeed there was a problem with dependencies. The ba3c6ca0cc202cd91f7614f7611f7f5a3266b76a fixed this issue.

**Comment by ashishk88** [comment]
Thanks, that fixed the issue.
