### ISSUE TITLE
UART not configured for hSens4 pins

### ISSUE THREAD

**Issue by sjauhri** [husarion/rosbot-firmware-new#4]
I am trying to set up a UART on the hSens4 pins of the CORE2 Board using the new mbedOS firmware. As per the husarion website (https://husarion.com/manuals/core2/#communication-interfaces), I should be able to use UART pins connected to both hSens3 and hSens4. However, I'm only able to do this with hSens3 and not with hSens4. Upon checking the code I see that the configuration/mapping of SENSE4 pins for UART may not have been done or not done correctly. (PinNames.h)

Some help with this would be really appreciated.

**Comment by byq77** [comment]
Hi, thanks for noticing the issue. The `PeripheralPins.c` was lacking the configuration for USART6 instance that is attached to pins 3 and 4 on hSens4 port. The 6f8f24fc5d6a408ed3a7277009691d344bc1ccb1 fixes the issue. I also added following constants, that might help differentiating between TX,RX pins:
* `SENS3_PIN3_UART_TX`
* `SENS3_PIN4_UART_RX`
* `SENS4_PIN3_UART_TX`
* `SENS4_PIN4_UART_RX`
