### ISSUE TITLE
providing the firmware file

### ISSUE THREAD

**Issue by heshananupama** [husarion/rosbot-firmware-new#5]
Is there any place to access the firmware file in the repository directly rather than building it from the scratch? In that way it would save a lot of time required to set everything up. Thanks

**Comment by lukaszmitka** [comment]
Firmware in binary form can be downloaded from [https://files.husarion.com/rosbot-firmware/](https://files.husarion.com/rosbot-firmware/)

**Comment by heshananupama** [comment]
Thank you very much @lukaszmitka
