### ISSUE TITLE
Building and Cleaning issues

### ISSUE THREAD

**Issue by sjauhri** [husarion/rosbot-firmware-new#6]
Hello,

I have the following issues when Building:

- Building using the "BUILD (RELEASE)" and "BUILD (DEBUG)" commands in VSCode always builds EVERYTHING. This is very time consuming especially when I just have some test code to build and flash.

- I always have to clean before any build. If I change just one file, mbed correctly scans and figures this out and only recompiles that file. However, when linking I get a multiple definitions error.

- RELEASE and DEBUG software doesn't build together. If I try to build both versions of software one after the other, I again get the multiple definitions linking error. For some reason mbed doesn't ignore the other version of the software during linking (See below).

![DEBUG_RELEASE_not_ignored](https://user-images.githubusercontent.com/43295601/89918357-35414b80-dbfa-11ea-9207-4bc016906d73.png)

**Comment by byq77** [comment]
Hi, 
Make sure, your BUILD directory has `.mbedignore` file that contains `*`. This informs mbed tools to omit  BUILD directory in linking process. You can also use `.mbedignore` files to explicitly tell the compiler what files should be ignored in build process. Here is more info on it: https://os.mbed.com/docs/mbed-os/v6.2/program-setup/build-rules.html#mbedignore

**Comment by sjauhri** [comment]
Thanks! This resolved the issue. 
I think this could happen to a lot of people that they delete the BUILD folder in order to clean everything and end up in this situation. Maybe an addition can be made in the ReadMe telling people not to do so ...
